// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnnsnnryudzjoppkwmac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdubnNubnJ5dWR6am9wcGt3bWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDY5NDUsImV4cCI6MjA2NDYyMjk0NX0.HFj-SmWcbSM1FhQAiaxQlQTY1IatTxlqrAX0GU7g0qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);